In [1]:
import numpy as np

In [2]:
# how time take numpy array and list array 
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]
c=[]
import time
start = time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)

1.6477265357971191


In [3]:
a = np.arange(10000000)
b = np.arange(10000000,20000000)
start = time.time()
c= a+b
print(time.time()-start)

0.08235955238342285


In [4]:
1.6/0.08

20.0

In [5]:
# size occupy in memory
a = [i for i in range(10000000)]
import sys
sys.getsizeof(a)


89095160

In [6]:
a = np.arange(10000000,dtype= np.int64)
sys.getsizeof(a)

80000112

In [7]:
a = np.arange(10000000,dtype= np.int32)
sys.getsizeof(a)

40000112

In [8]:
a= np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
# fancy indexing
a[[0,2,3],1:]

array([[ 1,  2,  3],
       [ 9, 10, 11],
       [13, 14, 15]])

In [10]:
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [11]:
# boolean indexing
a = np.random.randint(1,100,24).reshape(6,4)

In [12]:
a

array([[31, 18, 56, 97],
       [98, 67, 67, 86],
       [90, 94, 28, 15],
       [70, 45, 68,  1],
       [26,  9, 53, 74],
       [ 3, 25, 78, 34]])

In [13]:
# find all number greater  than 50
a>50

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [ True, False,  True, False],
       [False, False,  True,  True],
       [False, False,  True, False]])

In [14]:
# find all number greater  than 50
a[a>50]

array([56, 97, 98, 67, 67, 86, 90, 94, 70, 68, 53, 74, 78])

In [15]:
# find all number are even
a%2==0

array([[False,  True,  True, False],
       [ True, False, False,  True],
       [ True,  True,  True, False],
       [ True, False,  True, False],
       [ True, False, False,  True],
       [False, False,  True,  True]])

In [16]:
a[a%2==0]

array([18, 56, 98, 86, 90, 94, 28, 70, 68, 26, 74, 78, 34])

In [17]:
(a>50)&(a%2==0)

array([[False, False,  True, False],
       [ True, False, False,  True],
       [ True,  True, False, False],
       [ True, False,  True, False],
       [False, False, False,  True],
       [False, False,  True, False]])

In [18]:
# find all number grater than 50 and are even
# here we use bitwise & bcz we deal with boolean data

a[(a>50)&(a%2==0)]

array([56, 98, 86, 90, 94, 70, 68, 74, 78])

In [19]:
a[~(a%7==0)]
a[a%7!=0]

array([31, 18, 97, 67, 67, 86, 90, 94, 15, 45, 68,  1, 26,  9, 53, 74,  3,
       25, 78, 34])

In [20]:
# broadcasting :- we use this techni. called vectorization numpy avoid for loop 

In [21]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [25]:
# sigmoid
def sigmoid(array):
    return 1/(1+np.exp(-(array)))


a = np.arange(100)

sigmoid(a)


array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661,
       0.9999546 , 0.9999833 , 0.99999386, 0.99999774, 0.99999917,
       0.99999969, 0.99999989, 0.99999996, 0.99999998, 0.99999999,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.     

In [31]:
# mean  squared error
actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

def mse(actual,predicted):
    return np.mean((actual-predicted)**2)


mse(actual,predicted)


316.76

In [34]:
# work witth missing value ->nan
a = np.array([1,2,3,4,np.nan,6])

In [40]:
a[~np.isnan(a)]

array([1., 2., 3., 4., 6.])

AttributeError: 'numpy.ndarray' object has no attribute 'replace'