In [1]:
# numpy array creation


import numpy as np

# 1-D array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
# 2-d array 
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
# 3-d array 
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# float array
d = np.array([1,2,3],dtype=float)
print(d)

[1. 2. 3.]


In [5]:
# bool array
# 0 is False and other +ve and -ve value are True
e = np.array([0,-1,2,3],dtype=bool)
print(e)

[False  True  True  True]


In [6]:
# complex array
f = np.array([1,3,4],dtype=complex)
print(f)

[1.+0.j 3.+0.j 4.+0.j]


In [7]:
# arange function use for create a array for specific range
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [9]:
# reshape function use for change the dimension of array

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
# this is use for nutral network where each node connect with another node 
# those connection we called weight we assign those value useing ones
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
np.random.random((3,4))

array([[0.72877662, 0.81902985, 0.88696056, 0.73243338],
       [0.1862018 , 0.43648507, 0.11164484, 0.32324329],
       [0.78590076, 0.15731046, 0.44522441, 0.52470837]])

In [13]:
# linspace linear speratble points genterate for given range and how many point we want to create
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [14]:
# identity function use for indentity matrics creation
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# numpyarray access all the attributes of numpy class

a1 =np.arange(10)
a2 =np.arange(12,dtype=float).reshape(3,4)
a3 =np.arange(8).reshape(2,2,2)

In [16]:
# vetor bcz i d
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# matrix bcz 2 dimesion
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [18]:
# tensor bcz 3d
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
# ndim use for how many dimension in array
a1.ndim

1

In [20]:
a2.ndim

2

In [21]:
a3.ndim

3

In [22]:
# shape use for how many row and col in array
a2.shape

(3, 4)

In [23]:
# size use for how many item in array
a1.size

10

In [24]:
a2.size

12

In [25]:
a3.size

8

In [26]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [27]:
# astype use for change the datatype of existing array
# its mostly use for reduce the size of dataset
a2.astype(np.float32)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [28]:
a3 = a3.astype(float)
a3.dtype

dtype('float64')

In [29]:
# array operation
# ->scalar operation
# ->vector operation

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [30]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
# scalar operation 
# 1.arithematic
a1*3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [33]:
# 2.relational
a2>11

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [34]:
# vector operation we use those time when both array have same dimension
# ->arithematic
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [36]:
# numpy function

a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[87., 88., 86.],
       [79., 17., 95.],
       [77., 48., 23.]])

In [37]:
# max/min/sum/prod
np.max(a1)

95.0

In [46]:
# each in max
np.max(a1,axis=1)

array([88., 95., 77.])

In [47]:
np.min(a1)

17.0

In [48]:
# each row in min
np.min(a1,axis=1)

array([86., 17., 23.])

In [39]:
np.sum(a1)

600.0

In [49]:
# each row sum
np.sum(a1,axis=1)

array([261., 191., 148.])

In [41]:
np.prod(a1)

7141012487642880.0

In [50]:
# each row product
np.prod(a1,axis=1)

array([658416., 127585.,  85008.])

In [58]:
# mean/median/std/var
np.mean(a1)
# entrie matrix on mean calculation 

66.66666666666667

In [59]:
# each row mean
np.mean(a1,axis=1)

array([87.        , 63.66666667, 49.33333333])

In [60]:
np.median(a1)
# enitre matrix on median calculation 

79.0

In [61]:
a1

array([[87., 88., 86.],
       [79., 17., 95.],
       [77., 48., 23.]])

In [62]:
# each row media
np.median(a1,axis=1)

array([87., 79., 48.])

In [63]:
np.std(a1)
# entrie matrix on standard deviation calculation

27.94041278626117

In [64]:
# each row standard deviation
np.std(a1,axis=1)

array([ 0.81649658, 33.63860216, 22.06555888])

In [65]:
np.var(a1)
# entire matrix upon variance calculation

780.6666666666666

In [66]:
# each row variance
np.var(a1,axis=1)

array([6.66666667e-01, 1.13155556e+03, 4.86888889e+02])

axis =1 means row wise operation
axis =0 means col wise operaion perform

In [71]:
# dot product
# we apply dot product when our 1st martix total cal equal to 2nd matrix total row are equal
# and dot product resultant always 1st matrix row and 2nd matrix col 
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [72]:
# log and exponents
np.log(a1)
np.exp(a1)

array([[6.07603023e+37, 1.65163625e+38, 2.23524660e+37],
       [2.03828107e+34, 2.41549528e+07, 1.81123908e+41],
       [2.75851345e+33, 7.01673591e+20, 9.74480345e+09]])

In [74]:
np.round(np.random.random((2,3))*100)

array([[54., 63., 97.],
       [97.,  5.,  3.]])

In [75]:
np.floor(np.random.random((2,3))*100)

array([[83.,  7., 18.],
       [21., 48., 22.]])

In [76]:
np.ceil(np.random.random((2,3))*100)

array([[67., 20., 78.],
       [66., 52., 53.]])

In [78]:
# indexing and slicing

a1= np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3= np.arange(8).reshape(2,2,2)

In [95]:
# index example in index we get only one value

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [84]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
a2[1,2]

6

In [86]:
a2[2,3]
# here 2 represent row and 3 represent col

11

In [87]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [91]:
a3[1,0,1]
# here 1 represent which 2d array in 3d and 0 represent row and 1 represent col


5

In [92]:
a3[0,1,1]

3

In [93]:
a3[1,1,1]

7

In [94]:
a3[0,0,1]

1

In [96]:
# slicing example  in slicing we extract multiple value  

In [97]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
a1[2:5:1]

array([2, 3, 4])

In [100]:
a1[-3:]

array([7, 8, 9])

In [101]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
a2[0,:]

array([0, 1, 2, 3])

In [110]:
a2[:,2]

array([ 2,  6, 10])

In [113]:
a2[2,3]

11

In [114]:
a2[0,:]

array([0, 1, 2, 3])

In [115]:
a2[:,1]

array([1, 5, 9])

In [116]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
a2[1,1:3]

array([5, 6])

In [119]:
a2[2,1:3]

array([ 9, 10])

In [120]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [122]:
a2[0::2,0::3]

array([[ 0,  3],
       [ 8, 11]])

In [123]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
a2[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [125]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [126]:
a3 = np.arange(27).reshape(3,3,3)

In [127]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [128]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [129]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [134]:
a3[::2,:,::2]

array([[[ 0,  2],
        [ 3,  5],
        [ 6,  8]],

       [[18, 20],
        [21, 23],
        [24, 26]]])

In [137]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [138]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [139]:
a3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

In [141]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [143]:
# transpose convert into row->col and col-> row
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [144]:
# ravel :- ravel convet all dimension into 1d

In [147]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [148]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [150]:
for i in a3.ravel():
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [159]:
# stacking :- stacking use for multiple data set combine come from different source amd shape is same
# ->horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [160]:
# horizondatal stacking example
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [161]:
# vertical stacking example
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [163]:
# spliting
# ->horizontal split
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [164]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [166]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [ ]:
|