In [1]:
import numpy as np

a = np.random.randint(1,100,15)
b = np.random.randint(1,100,24).reshape(6,4)

In [2]:
a

array([98, 45, 59, 38, 34, 23, 95, 79, 91, 81, 12,  8, 65, 44, 22])

In [3]:
b

array([[52,  2, 47, 81],
       [89, 24, 73, 61],
       [51, 75, 83, 57],
       [84,  3,  5, 52],
       [52, 38, 12, 89],
       [10, 14, 85, 51]])

In [4]:
# sort method
# ascending order
np.sort(a)

array([ 8, 12, 22, 23, 34, 38, 44, 45, 59, 65, 79, 81, 91, 95, 98])

In [5]:
# ascending order there axis =0 means col and axis =1 means row ,kind{‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}, optional
np.sort(b,axis=0)

array([[10,  2,  5, 51],
       [51,  3, 12, 52],
       [52, 14, 47, 57],
       [52, 24, 73, 61],
       [84, 38, 83, 81],
       [89, 75, 85, 89]])

In [6]:
# decending order
np.sort(a)[::-1]

array([98, 95, 91, 81, 79, 65, 59, 45, 44, 38, 34, 23, 22, 12,  8])

In [7]:
np.sort(b,axis=0)[::-1]

array([[89, 75, 85, 89],
       [84, 38, 83, 81],
       [52, 24, 73, 61],
       [52, 14, 47, 57],
       [51,  3, 12, 52],
       [10,  2,  5, 51]])

In [8]:
# append method

a

array([98, 45, 59, 38, 34, 23, 95, 79, 91, 81, 12,  8, 65, 44, 22])

In [9]:
np.append(a,200)

array([ 98,  45,  59,  38,  34,  23,  95,  79,  91,  81,  12,   8,  65,
        44,  22, 200])

In [10]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[52.,  2., 47., 81.,  1.],
       [89., 24., 73., 61.,  1.],
       [51., 75., 83., 57.,  1.],
       [84.,  3.,  5., 52.,  1.],
       [52., 38., 12., 89.,  1.],
       [10., 14., 85., 51.,  1.]])

In [11]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

In [12]:
np.concatenate((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [14]:
e= np.array([1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9])

In [15]:
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.expand_dims(a,axis=0)

array([[98, 45, 59, 38, 34, 23, 95, 79, 91, 81, 12,  8, 65, 44, 22]])

In [17]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [18]:
np.expand_dims(a,axis=1)

array([[98],
       [45],
       [59],
       [38],
       [34],
       [23],
       [95],
       [79],
       [91],
       [81],
       [12],
       [ 8],
       [65],
       [44],
       [22]])

In [19]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [20]:
# find all indices woth value greater than 50
np.where(a>50)

(array([ 0,  2,  6,  7,  8,  9, 12]),)

In [21]:
# replace all values > 50 with 0
# np.where(condition,true,false)
np.where(a>50,0,a)

array([ 0, 45,  0, 38, 34, 23,  0,  0,  0,  0, 12,  8,  0, 44, 22])

In [22]:
# replace all value those are even and replace with 0
np.where(a%2==0,0,a)

array([ 0, 45, 59,  0,  0, 23, 95, 79, 91, 81,  0,  0, 65,  0,  0])

In [23]:
a

array([98, 45, 59, 38, 34, 23, 95, 79, 91, 81, 12,  8, 65, 44, 22])

In [24]:
np.argmax(a)

0

In [25]:
np.argmax(b)

4

In [26]:
np.argmax(b,axis=0)

array([1, 2, 5, 4])

In [28]:
np.argmax(b,axis=1)

array([3, 0, 2, 0, 3, 2])

In [29]:
np.argmin(b,axis=0)

array([5, 0, 3, 5])

In [30]:
np.argmin(b,axis=1)

array([1, 1, 0, 1, 2, 0])

In [31]:
np.argmin(b)

1

In [32]:
np.cumsum(a)

array([ 98, 143, 202, 240, 274, 297, 392, 471, 562, 643, 655, 663, 728,
       772, 794])

In [33]:
np.cumsum(b,axis=1)

array([[ 52,  54, 101, 182],
       [ 89, 113, 186, 247],
       [ 51, 126, 209, 266],
       [ 84,  87,  92, 144],
       [ 52,  90, 102, 191],
       [ 10,  24, 109, 160]])

In [34]:
b

array([[52,  2, 47, 81],
       [89, 24, 73, 61],
       [51, 75, 83, 57],
       [84,  3,  5, 52],
       [52, 38, 12, 89],
       [10, 14, 85, 51]])

In [35]:
np.cumsum(b,axis=0)

array([[ 52,   2,  47,  81],
       [141,  26, 120, 142],
       [192, 101, 203, 199],
       [276, 104, 208, 251],
       [328, 142, 220, 340],
       [338, 156, 305, 391]])

In [36]:
np.cumprod(a)

array([                  98,                 4410,               260190,
                    9887220,            336165480,           7731806040,
               734521573800,       58027204330200,     5280475594048200,
         427718523117904200,  5132622277414850400,  4167490071899699968,
       -5814306432162776320,  2424934016771564544, -1991683852154234880])

In [37]:
np.percentile(a,100)

98.0

In [41]:
np.percentile(b,100,axis=1)

array([81., 89., 83., 84., 89., 85.])

In [40]:
b

array([[52,  2, 47, 81],
       [89, 24, 73, 61],
       [51, 75, 83, 57],
       [84,  3,  5, 52],
       [52, 38, 12, 89],
       [10, 14, 85, 51]])

In [42]:
np.percentile(b,100,axis=0)

array([89., 75., 85., 89.])

In [43]:
np.percentile(b,100)

89.0

In [44]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 1, 2, 2, 2, 1, 1, 1, 1, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [46]:
salary = np.array([10000,20000,30000,40000,50000,60000,70000])
experience = np.array([1,3,2,4,2,3,5])

np.corrcoef(salary,experience)

array([[1.       , 0.6882472],
       [0.6882472, 1.       ]])

In [47]:
a

array([98, 45, 59, 38, 34, 23, 95, 79, 91, 81, 12,  8, 65, 44, 22])

In [48]:
item=[10,20,30,40,50,60,70,80,90,100]

np.isin(a,item)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [53]:
f= np.array([98, 45, 59, 38, 34, 23, 95, 79, 91, 30, 12,  30, 65, 20, 30])

In [54]:
np.isin(f,item)

array([False, False, False, False, False, False, False, False, False,
        True, False,  True, False,  True,  True])

In [57]:
f[np.isin(f,item)]

array([30, 30, 20, 30])

In [58]:
a

array([98, 45, 59, 38, 34, 23, 95, 79, 91, 81, 12,  8, 65, 44, 22])

In [59]:
np.flip(a)

array([22, 44, 65,  8, 12, 81, 91, 79, 95, 23, 34, 38, 59, 45, 98])

In [60]:
np.flip(b,axis=0)

array([[10, 14, 85, 51],
       [52, 38, 12, 89],
       [84,  3,  5, 52],
       [51, 75, 83, 57],
       [89, 24, 73, 61],
       [52,  2, 47, 81]])

In [61]:
b

array([[52,  2, 47, 81],
       [89, 24, 73, 61],
       [51, 75, 83, 57],
       [84,  3,  5, 52],
       [52, 38, 12, 89],
       [10, 14, 85, 51]])

In [62]:
np.flip(b,axis=1)

array([[81, 47,  2, 52],
       [61, 73, 24, 89],
       [57, 83, 75, 51],
       [52,  5,  3, 84],
       [89, 12, 38, 52],
       [51, 85, 14, 10]])

In [63]:
a

array([98, 45, 59, 38, 34, 23, 95, 79, 91, 81, 12,  8, 65, 44, 22])

In [64]:
np.put(a,[0,1],[980,450])

In [65]:
a

array([980, 450,  59,  38,  34,  23,  95,  79,  91,  81,  12,   8,  65,
        44,  22])